module.exports = {
  Continue:   100,                // {code:'100',message: 'Continue'},
  Switching:  101,                // {code:'101',message: 'Switching Protocols'},
  Processing: 102,                 // {code:'102',message: 'Processing'},
  OK:         200,                 // {code:'200',message: 'OK'},                                  // using
  Created:    201,                 // {code:'201',message: 'Created'},                             // using
  Accepted:   202,                 // {code:'202',message: 'Accepted'},
  Non_Authoritative_Info:        {code:'203',message: 'Non-Authoritative Information'},
  No_Content:                    {code:'204',message: 'No Content'},
  Reset_Content:                 {code:'205',message: 'Reset Content'},
  Partial_Content:               {code:'206',message: 'Partial Content'},
  Multi_Status:                  {code:'207',message: 'Multi-Status'},
  Multiple_Choices:              {code:'300',message: 'Multiple Choices'},
  Moved_Permanently:             {code:'301',message: 'Moved Permanently'},
  Moved_Temporarily:             {code:'302',message: 'Moved Temporarily'},
  See_Other:                     {code:'303',message: 'See Other'},
  Not_Modified:                  {code:'304',message: 'Not Modified'},
  Use_Proxy:                     {code:'305',message: 'Use Proxy'},
  Temporary_Redirect:            {code:'307',message: 'Temporary Redirect'},
  Bad_Request:  400,          //       {code:'400',message: 'Bad Request'},                           // using
  Unauthorized: 401,          //       {code:'401',message: 'Unauthorized'},                          // using
  Unauthorized:                  {code:'402',message: 'Payment Required'},                      
  Forbidden:                     {code:'403',message: 'Forbidden'},
  Not_Found:                     {code:'404',message: 'Not Found'},
  Method_Not_Allowed:            {code:'405',message: 'Method Not Allowed'},
  Not_Acceptable:                {code:'406',message: 'Not Acceptable'},
  Proxy_Authentication_Required: {code:'407',message: 'Proxy Authentication Required'},
  Request_Time_out:              {code:'408',message: 'Request Time-out'},
  Conflict:                      {code:'409',message: 'Conflict'},
  Gone:                          {code:'410',message: 'Gone'},
  Length_Required:               {code:'411',message: 'Length Required'},
  Precondition_Failed:           {code:'412',message: 'Precondition Failed'},
  Request_Entity_Too_Large:      {code:'413',message: 'Request Entity Too Large'},
  Request_URI_Too_Large:         {code:'414',message: 'Request-URI Too Large'},
  Unsupported_Media_Type:        {code:'415',message: 'Unsupported Media Type'},
  Requested_Range_Not_Satisfiable:{code:'416',message: 'Requested Range Not Satisfiable'},
  Expectation_Failed:            {code:'417',message: 'Expectation Failed'},
  teapot:                        {code:'418',message: 'I\'m a teapot'},
  Unprocessable_Entity:          {code:'422',message: 'Unprocessable Entity'},
  Locked:                        {code:'423',message: 'Locked'},
  Failed_Dependency:             {code:'424',message: 'Failed Dependency'},
  Unordered_Collection:          {code:'425',message: 'Unordered Collection'},
  Upgrade_Required:              {code:'426',message: 'Upgrade Required'},
  Precondition_Required:         {code:'428',message: 'Precondition Required'},
  Too_Many_Requests:             {code:'429',message: 'Too Many Requests'},
  Request_Header_Fields_Too_Large: {code:'431',message: 'Request Header Fields Too Large'},
  Server_Error:  500,   //    {code:'500',message: 'Internal Server Error'},                     // using
  Not_Implemented:               {code:'501',message: 'Not Implemented'},
  Bad_Gateway:                   {code:'502',message: 'Bad Gateway'},
  Service_Unavailable:           {code:'503',message: 'Service Unavailable'},
  Gateway_Time_out:              {code:'504',message: 'Gateway Time-out'},
  HTTP_Version_Not_Supported:    {code:'505',message: 'HTTP Version Not Supported'},
  Variant_Also_Negotiates:       {code:'506',message: 'Variant Also Negotiates'},
  Insufficient_Storage:          {code:'507',message: 'Insufficient Storage'},
  Bandwidth_Limit_Exceeded:      {code:'509',message: 'Bandwidth Limit Exceeded'},
  Not_Extended:                  {code:'510',message: 'Not Extended'},
  Network_Authentication_Required:{code:'511',message: 'Network Authentication Required'}
}