import { ObjectId } from "mongoose";

export interface IBimaGarage {
  firstname: string,
  lastname: string,
  email: string,
  primary_phone: string,
  dateofbirth: string,
  gender: string,
  zip_code: string,
  city: string,
  address_line1:string
  district: string,
  state:  string,
  tpa: number,
  insuranceco: number,
  uhid: string,
  policy_no: number,
  inhouse_tpa: boolean,
  sum_insured: number,
  is_corporate: boolean,
  corporate_name: string,  
  policy_startdt: Date,
  policy_enddt: Date
}

export interface IBGPatientDTO {
  policy_doc: any;
  firstname: string,
  lastname: string,
  email: string,
  primary_phone: string,
  dateofbirth: string,
  gender: string,
  zip_code: string,
  city: string,
  address_line1:string
  district: string,
  state:  string,
  tpa: number,
  insuranceco: number,
  uhid: string,
  policy_no: number,
  inhouse_tpa: boolean,
  sum_insured: number,
  is_corporate: boolean,
  corporate_name: string,  
  policy_startdt: Date,
  policy_enddt: Date,
 
}


export interface IBGcase {
  insuranceco: string,
  tpa: string,
  customer: string,
  case_rep: string,
  claim_status: string,
  ipdno: string,
  contact_name: string,
  contact_number: string,
  admission_type:string
  treatment_type: string,
  description:  string,
  admission_date: string,
  discharge_date: string,
  primary_doc: string,
  ailment: string,
  days_of_stay: number,
  room_type: string,
  deposit_amount: string,
  files: string,
  claim_number: string,  
  preauth_inidate: string,
  preauth_iniamt: string,
  prauth_apdate: string,
  preauth_apamt: string,
  finalapreq_date: string,
  expense_pharmacy: string,
  expense_diagnosis: string,
  expense_total: string,
  billing_date: string,
  fappr_date: string,
  fappr_amt: string,
  fappr_hosp_disc: string,
  fappr_deduction_amt: string,
  fappr_deduction_reason: string,
  file_sentdate: string,
  tracking_no: string,
  courier_company: string,
  notes: string,
  utrno: string,
  utr_date: string,
  settle_date: string,
  settlement_letter: string,
  settlement_action: string,
  deduction_amount: string,
  deduction_reason: string,
  deduction_tds: string,
  cheque_amount: string,
  queryp_comments: string,
  rejection_comments: string,
  preauth_form_status: number,
  preauth_form: string,
  final_appr_letter: string,
  settlement_letter_file: string,
  created_on: string,
  created_on_time: string,
  preauth_init_time: string,
  preauth_app_time: string,
  fappr_init_time: string,
  fappr_received_timestamp: string,
  file_dispatch_time: string,
  pending_file_dispatch_time: string,
  claim_settled_time: string,
  mopreauth_appr: string,
  mofinappr_appr: string,
  mo_comments: string,
  mofinappr_comments: string,
  nursing_charges: string,
  room_charges: string,
  other_charges: string,
  mou_deduction_amt: string,
  non_medical_amt: string,
  co_pay_d_amt: string,
  other_deduction: string,
  pre_auth_appr_letter: string,
  claim_rejec_letter: string,
  fin_bill_summ: string,
  courier_receipt: string
}